import networkx as nx 
G = nx.DiGraph()
G.add_node('G1',type='input')
G.add_node('G2',type='input')
G.add_node('G3',type='input')
G.add_node('G4',type='input')
G.add_node('G5',type='input')
G.add_node('G8',type='gate',gatetype='nand')
G.add_node('G9',type='gate',gatetype='nand')
G.add_node('G12',type='gate',gatetype='nand')
G.add_node('G15',type='gate',gatetype='nand')
G.add_node('G16',type='gate',gatetype='nand')
G.add_node('G17',type='gate',gatetype='nand')
G.add_node('output2',type='output')
G.add_node('output1',type='output')
G.add_node('fanout1',type='fanout')
G.add_node('fanout3',type='fanout')
G.add_node('fanout2',type='fanout')
G.add_edges_from([('G3', 'fanout1'),('G12', 'fanout3'),('G9', 'fanout2'),('G17', 'output2'),('G16', 'output1'),('G1', 'G8'),('fanout1', 'G8'),('fanout1', 'G9'),('G4', 'G9'),('G2', 'G12'),('fanout2', 'G12'),('fanout2', 'G15'),('G5', 'G15'),('G8', 'G16'),('fanout3', 'G16'),('fanout3', 'G17'),('G15', 'G17')], value_non_fault='x',value_faulty='x', fault='',cc0=0,cc1=0)
G.add_edge('G1','G8', value_non_fault='x',value_faulty='x', fault='',cc0=1,cc1=1)
G.add_edge('G2','G12', value_non_fault='x',value_faulty='x', fault='',cc0=1,cc1=1)
G.add_edge('G3','fanout1', value_non_fault='x',value_faulty='x', fault='',cc0=1,cc1=1)
G.add_edge('G4','G9', value_non_fault='x',value_faulty='x', fault='',cc0=1,cc1=1)
G.add_edge('G5','G15', value_non_fault='x',value_faulty='x', fault='',cc0=1,cc1=1)


G.add_edge('fanout3','G17', value_non_fault='x',value_faulty='x',fault='sa1')
